### ISSUE TITLE
member function destroyScreen(screen); not found

### ISSUE THREAD

**Issue by ghost** [maui-mer-packaging/qtwayland#2]
in branch output55:

qtwayland/src/client/qwaylanddisplay.cpp:169: error:
'class QtWaylandClient::QWaylandIntegration' has no member named 'destroyScreen'
         mWaylandIntegration->destroyScreen(screen);

**Comment by plfiorini** [comment]
Guess that you are building output55 with Qt 5.4.x, if that's the case please build output54

**Comment by lordadamson** [comment]
No, I'm pretty sure I'm using 5.5 , got an idea what could that mean?

**Comment by ghost** [comment]
yes indeed, thanks a lot :))
